# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
default_language_version:
  python: python3.10
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: debug-statements
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
      - id: fix-byte-order-marker
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: detect-private-key
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["--severity-level", "high", "--confidence-level", "high"]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter # runs on both *.py and *.ipynb
        language_version: python 3.10
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.260"
    hooks:
      - id: ruff
        args: [--no-fix, --exit-non-zero-on-fix, --config=pyproject.toml]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
        args: ["--directory=pointing"]
        files: pyproject.toml$
      - id: poetry-lock
        args: ["--no-update", "--directory=pointing"]
        files: (pyproject.toml|poetry.lock)$
      - id: poetry-check
        args: ["--directory=tracking"]
        files: pyproject.toml$
      - id: poetry-lock
        args: ["--no-update", "--directory=tracking"]
        files: (pyproject.toml|poetry.lock)$
